project:
  name: quickstart-neo4j
tests:
  default:
    template: ./templates/neo4j.template.yaml
    parameters:
      Password: "foo123"
      GraphDatabaseVersion: "5.1.0"
      NumberOfServers: "3"
      SSHCIDR: "0.0.0.0/0"
      InstallGraphDataScience: "False"
      InstallBloom: "False"
    stack_name: "tcat"
    regions:
      - us-east-1
