project:
  name: quickstart-neo4j
tests:
  default:
    template: ./templates/neo4j.template.yaml
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-neo4j/
    regions:
    - us-east-2
