AWSTemplateFormatVersion: '2010-09-09'
Description: Neo4j Graph Data Science. Do Not Remove Apache License Version 2.0.(qs-1shnl7a6p)
Parameters:
  GraphDatabaseVersion:
    Description: Neo4j Graph Database Version
    Type: String
    Default: '4.4.0'
    AllowedValues:
      - '4.4.0'
      - '4.3.7'

  GraphDataScienceVersion:
    Description: Neo4j Graph Data Science Version
    Type: String
    Default: '1.8.0'
    AllowedValues:
      - '1.8.0'
      - '1.7.3'

  BloomVersion:
    Description: Neo4j Graph Data Science Version
    Type: String
    Default: '2.0.0'
    AllowedValues:
      - '2.0.0'

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.medium
      - t3.large
      - t3.xlarge
      - r6i.large
      - r6i.xlarge
      - r6i.2xlarge
      - r6i.4xlarge
      - r6i.8xlarge
      - r6i.12xlarge
      - r6i.16xlarge
      - r6i.24xlarge
      - r6i.32xlarge

  DiskSize:
    Description: Size in GB of the EBS volume on each node
    Type: Number
    Default: 100

  Password:
    Description: Password for Neo4j
    Type: String
    MinLength: 6
    NoEcho: true

  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

  AMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  Neo4jAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Fn::GetAZs: ''
      LaunchConfigurationName:
        Ref: Neo4jLaunchConfiguration
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1

  Neo4jLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AMIID
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
      - Ref: Neo4jExternalSecurityGroup
      - Ref: Neo4jInternalSecurityGroup
      KeyName:
        Ref: KeyName
      EbsOptimized: true
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize:
            Ref: DiskSize
          VolumeType: gp3
          Encrypted: true
      UserData:
        Fn::Base64:
          !Join
          - ''
          - - "#!/bin/bash\n"
            - "echo Running startup script...\n"

            - "graphDatabaseVersion="
            - Ref: GraphDatabaseVersion
            - "\n"

            - "graphDataScienceVersion="
            - Ref: GraphDataScienceVersion
            - "\n"

            - "bloomVersion="
            - Ref: BloomVersion
            - "\n"

            - "password="
            - Ref: Password
            - "\n"

            - "echo Adding neo4j yum repo...\n"
            - "rpm --import https://debian.neo4j.com/neotechnology.gpg.key\n"
            - "echo \""
            - "[neo4j]\n"
            - "name=Neo4j Yum Repo\n"
            - "baseurl=http://yum.neo4j.com/stable\n"
            - "enabled=1\n"
            - "gpgcheck=1\" > /etc/yum.repos.d/neo4j.repo\n"

            - "echo Installing Graph Database...\n"
            - "export NEO4J_ACCEPT_LICENSE_AGREEMENT=yes\n"
            - "yum -y install neo4j-enterprise-${graphDatabaseVersion}\n"

            - "echo Configuring network in neo4j.conf...\n"
            - "sed -i 's/#dbms.default_listen_address=0.0.0.0/dbms.default_listen_address=0.0.0.0/g' /etc/neo4j/neo4j.conf\n"
            - "publicHostname=$(curl -s http://169.254.169.254/latest/meta-data/public-hostname)\n"
            - "sed -i s/#dbms.default_advertised_address=localhost/dbms.default_advertised_address=${publicHostname}/g /etc/neo4j/neo4j.conf\n"

            - "echo Installing Graph Data Science...\n"
            - "curl -s \"https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/neo4j-graph-data-science-${graphDataScienceVersion}-standalone.zip\" -o neo4j-graph-data-science-${graphDataScienceVersion}-standalone.zip"
            - "unzip neo4j-graph-data-science-${graphDataScienceVersion}-standalone.zip\n"
            - "mv neo4j-graph-data-science-${graphDataScienceVersion}.jar /var/lib/neo4j/plugins"

            - "echo Configuring Graph Data Science...\n"
            - "#dbms.security.procedures.unrestricted=gds.*"
            - "#dbms.security.procedures.allowlist=gds.*"

            - "echo Installing Bloom...\n"
            - "curl -s \"https://neo4j.com/artifact.php?name=neo4j-bloom-${bloomVersion}.zip\" -o neo4j-bloom-${bloomVersion}.zip"

            - "service neo4j start\n"
            - "neo4j-admin set-initial-password ${password}\n"

  Neo4jExternalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and Neo4j External Ports
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 7474
        ToPort: 7474
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 7473
        ToPort: 7473
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 7687
        ToPort: 7687
        CidrIp: 0.0.0.0/0

  Neo4jInternalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable Neo4j Internal Ports
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5000
        ToPort: 5000
        SourceSecurityGroupName: !Ref Neo4jExternalSecurityGroup
      - IpProtocol: tcp
        FromPort: 6000
        ToPort: 6000
        SourceSecurityGroupName: !Ref Neo4jExternalSecurityGroup
      - IpProtocol: tcp
        FromPort: 7000
        ToPort: 7000
        SourceSecurityGroupName: !Ref Neo4jExternalSecurityGroup
      - IpProtocol: tcp
        FromPort: 7688
        ToPort: 7688
        SourceSecurityGroupName: !Ref Neo4jExternalSecurityGroup
      - IpProtocol: tcp
        FromPort: 2003
        ToPort: 2003
        SourceSecurityGroupName: !Ref Neo4jExternalSecurityGroup
      - IpProtocol: tcp
        FromPort: 2004
        ToPort: 2004
        SourceSecurityGroupName: !Ref Neo4jExternalSecurityGroup
      - IpProtocol: tcp
        FromPort: 3637
        ToPort: 3637
        SourceSecurityGroupName: !Ref Neo4jExternalSecurityGroup
      - IpProtocol: tcp
        FromPort: 5005
        ToPort: 5005
        SourceSecurityGroupName: !Ref Neo4jExternalSecurityGroup
